parameters:
#    nanaweb_ec.example.class: Nanaweb\EcBundle\Example

services:
#    nanaweb_ec.example:
#        class: %nanaweb_ec.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
